name: "OSC Sender"
version: "1.0.0"
slug: "osc_sender"
description: "Sendet Open Sound Control (OSC) Nachrichten über eine einfache HTTP-API oder CLI."
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
  - i386
startup: "application"
boot: "auto"
host_network: true
options:
  default_ip: "127.0.0.1"
  default_port: 8000
  default_address: "/test"
  default_value: "1"
schema:
  default_ip: str
  default_port: int
  default_address: str
  default_value: str
